### ISSUE TITLE
Solve security issues | Back End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets-api#118]
### Objective
Fix actual issues related to security and check it will not affect API's current functionalities.

---

### Description
After some time without new work (except on last weeks), I have found some security issues that I will focus on this issue in order to maintain project and system integrity.

---

### Tasks
- [x] Fix every founded security error
- [x] Check main functionality works as expected
- [x] Check build process works as expected
- [x] Check test script works as expected

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
The errors have been founded thank you to [Snyk](https://app.snyk.io/), a security service that informs to repo's owners about every possible security breach.
