### ISSUE TITLE
Create a Pet event | Back End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets-api#141]
### Objective
Add a feature where the User will be able to add a new pet event

---

### Description
Now the User is able to add a manage its created pets, the next feature to add is add events that will create a log or journal por each Pet. This story cover the UI to create that event

---

### Tasks
- Development
  - [x] Create the query to fetch Pet's needed data.
  - [x] Create the mutation to create the event.
  - [x] Add/update the needed UT.

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
TBD
