### ISSUE TITLE
Create Widget to look created Pets and its composition | Back end

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets-api#26]
### Objective
Create the Widget to show created Pets to the User

---

### Description
This story will enable the first widget which will show the number of created Pets, as well as a series of colored labels with each Pet Type and its quantity.

---

### Tasks
- Research
  - **none**
- Development
  - [x] Create the query for `getMyPetsPopulation` endpoint
  - [x] Create the resolver for `getMyPetsPopulation` endpoint
  - [ ] Add and try to improve unit tests related to the implementation

---

### Tickets
| Relationship | Involved tickets |
| :--- | :---: |
| Is child from | [#26](https://github.com/NicolasOmar/my-pets/issues/26)
| In parent of | **none**
| Is related to | [#30](https://github.com/NicolasOmar/my-pets/issues/30), [#32 FE](https://github.com/NicolasOmar/my-pets/issues/32)
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
Other features (like toggle visibility, change what subset of data is visible, change each widget size and position) will be added in the future (after v0.2 is fully released)
