### ISSUE TITLE
Integrate Typescript | Back End

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets-api#353]
### Objective
Integrate Typescript technology into the project's code.

---

### Description
To revitalize the project and ease the development experience (after gathering new information from past and current projects), I decided to include Typescript as part of the repo's tech stack.

---

### Tasks
- Investigation
  - [x] Find the easiest way to include the technology on the repo.
  - [x] Sieze alternatives to update code to Typescript API calls.
  - [x] Sieze alternatives to update code to Typescript in functions.
  - [x] Sieze alternatives to update code to Typescript in unit tests.
- Development
  - [x] Update the API's code to Typescript.
  - [x] Update the function's code to Typescript.
  - [ ] Update the unit test code for Typescript.

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
TBD

**Comment by NicolasOmar** [comment]
Possible starting point on [this link](https://www.youtube.com/watch?v=qy8PxD3alWw&ab_channel=ColtSteele)

**Comment by NicolasOmar** [comment]
- I also started the migration based on [this article](https://www.digitalocean.com/community/tutorials/setting-up-a-node-project-with-typescript).
