### ISSUE TITLE
Add unit testing runs on Github Actions

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-pets-api#54]
### Objective
Add a Jest suite runtime to one of MyPets API's Github Action connected to a MongoDB connection.

---

### Description
To reduce unnecessary code (from the `coverage` folder), I need to move Jest's runtime to an existing Github Action where the UT coverage is collected by `Codecov` and `SonarCloud` services for analysis and results display.
The problem could be to find a way to connect the UT suite to a MongoDB instance by an environment variable from Github's secrets and passed to the Action as a `env` key.

---

### Tasks
- [x] Find bibliography to pass a env key from repo's secrets to the Action.
- [x] Test modified Action on the PR
- [x] Add to `.gitignore` file the `coverage` folder

---

### Ticket relationships
| Relationship | Involved tickets |
| :--- | :---: |
| Is child of | **none**
| In parent of | **none**
| Is related to | **none**
| Is blocked by | **none**
| It blocks |  **none**

---

### Technical notes
None
